services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgreSQL:/var/lib/postgresql/data
volumes:
  redis:
    driver: local
