services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgreSQL:
    env_file:
      - .env
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5433:5433'
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - postgreSQL:/var/lib/postgresql/data
volumes:
  redis:
    driver: local
  postgreSQL:
