export enum ErrorCode {
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  INVALID_MESSAGE = 'INVALID_MESSAGE',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PROGRAM_NOT_FOUND = 'PROGRAM_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  NAME_IS_EMPTY = 'NAME_IS_EMPTY',
  NAME_MIN_LENGTH = 'NAME_MIN_LENGTH',
  NAME_MAX_LENGTH = 'NAME_MAX_LENGTH',
  PROGRAM_ID_MUST_BE_NUMBER = 'PROGRAM_ID_MUST_BE_NUMBER'
}
