name: Deploy Backend to Given Environment

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0

      # Caching global npm cache, as we're using pm2 (installed globally) to deploy the app
      # NOTE: the reason we don't want to install pm2 in devDependencies and install all of the project's dependencies here is
      # because the project being built on this CI/CD runner is pointless - pm2 pulls and builds the project from the repo for
      # us on the remote server, so we don't need to install the project's dependencies here.
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Install pm2
        run: npm install -g pm2

      # NOTE: the ssh key is stored in the relevant environment's secrets in the GitHub repo settings
      # The path the key is stored in should correspond to the key this environment is using in the ecosystem.config.js file
      - name: Write SSH key to filesystem for use by pm2
        run: |
          mkdir ~/.ssh/menklab
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/menklab/dracarys-backend-${{ inputs.environment }}

      # NOTE: the deployment name is (and in any future environments, should be) the same as the environment name
      - name: Deploy to ${{ inputs.environment }} using pm2
        run: pm2 deploy ecosystem.config.js ${{ inputs.environment }}

